---
apiVersion: v1
kind: Service
metadata:
  name: nacos-headless
  namespace: middleware
  labels:
    app: nacos-headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 8848
    name: server
    targetPort: 8848
  - port: 9848
    name: client-rpc
    targetPort: 9848
  - port: 9849
    name: raft-rpc
    targetPort: 9849
  - port: 7848
    name: old-raft-rpc
    targetPort: 7848
  selector:
    app: nacos
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nacos
  namespace: middleware
spec:
  volumeClaimTemplates:
  - metadata:
      name: nacos-data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: nacos-nas-sc
      resources:
        requests:
          storage: 100Gi
  serviceName: nacos-headless
  replicas: 3
  selector:
    matchLabels:
      app: nacos
  template:
    metadata:
      labels:
        app: nacos
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      nodeSelector:
        project: middleware
      tolerations:
      - key: "project"
        operator: "Equal"
        value: "middleware"
        effect: "NoSchedule"
      initContainers:
      - name: init-nacos
        image: nacos-registry.cn-hangzhou.cr.aliyuncs.com/nacos/nacos-server:v2.2.2
        command:
          - sh
          - -c
          - |
            cp -a /home/nacos/. /mnt/nacos/
        volumeMounts:
          - name: nacos-data
            mountPath: /mnt/nacos
      containers:
      - name: nacos
        imagePullPolicy: IfNotPresent
        image: nacos-registry.cn-hangzhou.cr.aliyuncs.com/nacos/nacos-server:v2.2.2
        volumeMounts:
        - name: nacos-data
          mountPath: /home/nacos
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
          limits:
            cpu: 2000m
            memory: 4Gi
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /nacos/actuator/health
            port: 8848
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /nacos/actuator/health
            port: 8848
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: 8848
          name: client
        - containerPort: 9848
          name: client-rpc
        - containerPort: 9849
          name: raft-rpc
        - containerPort: 7848
          name: old-raft-rpc
        env:
        - name: NACOS_REPLICAS
          value: "3"
        - name: MYSQL_SERVICE_HOST
          value: "127.0.0.1"
        - name: MYSQL_SERVICE_DB_NAME
          value: "nacos"
        - name: MYSQL_SERVICE_PORT
          value: "3306"
        - name: MYSQL_SERVICE_USER
          value: "nacos"
        - name: MYSQL_SERVICE_PASSWORD
          value: "UaRrNp26SNRuGxHKXg"
        - name: SPRING_DATASOURCE_PLATFORM
          value: "mysql"
        - name: NACOS_SERVER_PORT
          value: "8848"
        - name: NACOS_APPLICATION_PORT
          value: "8848"
        - name: PREFER_HOST_MODE
          value: "hostname"
        - name: NACOS_SERVERS
          value: "nacos-0.nacos-headless.middleware.svc.cluster.local:8848 nacos-1.nacos-headless.middleware.svc.cluster.local:8848 nacos-2.nacos-headless.middleware.svc.cluster.local:8848"
        - name: NACOS_AUTH_ENABLE
          value: "true"
        - name: NACOS_AUTH_CACHE_ENABLE
          value: "true"
        - name: NACOS_AUTH_TOKEN
          value: "VGhpc0lzTXlDdXN0b21TZWNyZXRLZXkwMTIzNDU2Nzg="
        - name: NACOS_AUTH_IDENTITY_KEY
          value: "identify"
        - name: NACOS_AUTH_IDENTITY_VALUE
          value: "identify"
        - name: TZ
          value: Asia/Shanghai
