apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos
  namespace: middleware
  labels:
    app: nacos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacos
  template:
    metadata:
      labels:
        app: nacos
    spec:
      containers:
      - env:
        - name: MYSQL_SERVICE_HOST #数据库地址
          value: "172.24.1.32"
        - name: MYSQL_SERVICE_PORT #数据库端口
          value: "33077"
        - name: MYSQL_SERVICE_DB_NAME #数据库名字
          value: "nacos"
        - name: MYSQL_SERVICE_USER #数据库用户
          value: "nacos"
        - name: MYSQL_SERVICE_PASSWORD  #数据库密码
          value: "ta4NvCFqclddl3#nHPF#"
        - name: MODE  #nacos部署模式为单机
          value: "standalone"
        - name: SPRING_DATASOURCE_PLATFORM
          value: "mysql"
        - name: NACOS_AUTH_ENABLE #开启鉴权
          value: "true"
        - name: NACOS_AUTH_CACHE_ENABLE #开启鉴权
          value: "true"
        - name: NACOS_AUTH_TOKEN  #默认的token生产环境需要更改，32位的Base64编码
          value: "cXdlcnR5dWlvcGFzZGZnaGprbHp4Y3Zibm1xd2Vhc2Q="
        - name: NACOS_AUTH_IDENTITY_KEY  #鉴权key
          value: "nacos"
        - name: NACOS_AUTH_IDENTITY_VALUE #鉴权值
          value: "Xueda2024.com"
        - name: TZ
          value: Asia/Shanghai
        image: nacos/nacos-server:v2.4.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /nacos/actuator/health
            port: 8848
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
            limits:
              cpu: 2000m
              memory: "4Gi"
            requests:
              cpu: 1000m
              memory: "2Gi"
        name: nacos
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /nacos/actuator/health
            port: 8848
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nacos
  name: nacos
  namespace: middleware
spec:
  ports:
  - port: 8848
    protocol: TCP
    name: http-web
    targetPort: 8848
  - port: 9848
    protocol: TCP
    name: client-rpc
    targetPort: 9848
  - port: 9849
    protocol: TCP
    name: raft-rpc
    targetPort: 9849
  - port: 7848
    protocol: TCP
    name: old-raft-rpc
    targetPort: 7848
  selector:
    app: nacos
  type: ClusterIP
